targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      slang_build_runner:
        enabled: true
        options:
          base_locale: en
          output_directory: 'lib/generated/i18n'
